dataframes:
  df1:
    date_column: 'date_time'
    granularity: 'WEEK'
    value_columns: ['A', 'B']
    merge_columns: ['region', 'division', 'branch']
    aggregation: 'mean'
    base_df_flag: True
  df2:
    date_column: 'time_stamp'
    granularity: 'DAY'
    value_columns: ['D', 'E']
    merge_columns: ['region', 'division']
    aggregation: 'mean'
    base_df_flag: False
  df3:
    date_column: 'date_time'
    granularity: 'MONTH'
    value_columns: ['G']
    merge_columns: ['region', 'branch']
    aggregation: 'mean'
    base_df_flag: False

model_stage:
  stage_1:
    model_type: bambi
    use_lagged_effects: true
    lagged_features:
      media_channel_clicks:
        lags: 3
        weights: [0.5, 0.25, 0.125]
    independent_vars: 
      - media_channel_clicks_weighted
      - other_channel_clicks
    output_column: leads
    hyperparams: {}
    fit_params:
      draws: 1000
      chains: 4
      tune: 700

  stage_2:
    model_type: linear_regression
    independent_vars: 
      - leads
      - campaign_spend
    output_column: sign_ups
    hyperparams: {}

  stage_3:
    model_type: lasso
    independent_vars: 
      - sign_ups
      - discounts
    output_column: revenue
    hyperparams:
      alpha: 0.1

